market:
  asset_class: crypto
  quote_currency: USDT
  timezone: UTC
  is_24h: true

defaults:
  tick_size: 0.01
  tick_value: 0.01
  trade_unit: 1
  min_qty: 0.001
  qty_precision: 3
  margin_rate: 0.0
  commission_rate: 0.001
  min_commission: 0.0
  transaction_tax: 0.0
  slippage_ticks: 2
  exchange: binance

instruments:
  BTC_USDT:
    symbol: BTCUSDT

  ETH_USDT:
    symbol: ETHUSDT
    min_qty: 0.01
    qty_precision: 2
