apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    url: quant_timescaledb:5432
    database: quant
    user: quant
    secureJsonData:
      password: quant_secret
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      postgresVersion: 1600
      timescaledb: true
    isDefault: false
    editable: false
