apiVersion: 1
datasources:
  - name: TimescaleDB
    uid: P40AE60E18F02DE32
    orgId: 1
    type: grafana-postgresql-datasource
    url: quant_timescaledb:5432
    database: quant
    user: quant
    secureJsonData:
      password: quant_secret
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: false
