apiVersion: 1
datasources:
  - name: TimescaleDB
    uid: P40AE60E18F02DE32
    orgId: 1
    type: grafana-postgresql-datasource
    url: $__env{VPS_DB_HOST}:5432
    database: quant
    user: grafana_reader
    secureJsonData:
      password: $__env{POSTGRES_GRAFANA_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
