"""Backtest engine, strategy protocol, cost model, and metrics.

Re-exports from subpackages for convenience.
"""

try:
    from ._version import __version__
except ImportError:
    # _version.py is generated by setuptools_scm at build/editable-install
    # time (gitignored, not committed) — missing only if librae is being
    # imported straight from a source tree that was never built/installed.
    __version__ = "0.0.0.dev0+unknown"

from .backtest.schema import (
    AccountPerformance,
    AllocationSnapshotPoint,
    BacktestOutput,
    EquityCurvePoint,
    FundingCashFlowRecord,
    PositionSnapshotPoint,
    RunMetadata,
    StrategyMetrics,
    RUN_ID_PATTERN,
)
from .backtest.engine import (
    AccountBacktestResult,
    AllocationSnapshot,
    Backtest,
    BacktestResult,
    EquitySnapshot,
    PortfolioSnapshot,
    PositionSnapshot,
)
from .core.cost_model import (
    CostModel,
    SymbolDescription,
    describe_symbols,
    margin_rate_from_absolute,
)
from .core.strategy import (
    AccountSnapshot,
    OrderIntent,
    OrderAction,
    Strategy,
    Context,
    Fill,
    MultiLegOrder,
    Position,
    PositionEventType,
    PositionSide,
    PortfolioTargets,
    StrategyDecision,
)
from .core.executor import (
    TradePnL,
    TradeResult,
    calc_equity,
    calc_trade_pnl,
    side_multiplier,
    simulate_fill,
)
from .core.funding import FundingCashFlow
from .core.metrics import (
    compute_all,
    compute_signal_outcomes,
    compute_trade_entry_outcomes,
    compute_trade_lifecycle_outcomes,
    generate_signal_mae_mfe_report,
    generate_trade_tearsheet,
    summarize_signal_mae_mfe,
    summarize_trade_entry_outcomes,
    summarize_trade_lifecycle_outcomes,
)
from .core.run_config import (
    AccountConfig,
    ExecutionPolicy,
    LiveMode,
    RiskPolicy,
    RunConfig,
    RunMode,
)
from .core.utils import generate_run_id, infer_timeframe, to_ccxt, to_canonical
from .config.market_config import MarketConfig, get_market
from .config.symbols import AvailableSymbol, available_symbols
from .artifacts import (
    ARTIFACT_SCHEMA_VERSION,
    TabularArtifact,
    build_backtest_artifact,
    build_market_data_artifact,
)

__all__ = [
    "__version__",
    "BacktestOutput",
    "AccountPerformance",
    "AccountBacktestResult",
    "AllocationSnapshotPoint",
    "EquityCurvePoint",
    "FundingCashFlowRecord",
    "PositionSnapshotPoint",
    "RunMetadata",
    "StrategyMetrics",
    "RUN_ID_PATTERN",
    "CostModel",
    "AccountConfig",
    "AccountSnapshot",
    "SymbolDescription",
    "describe_symbols",
    "margin_rate_from_absolute",
    "MarketConfig",
    "get_market",
    "AvailableSymbol",
    "available_symbols",
    "ARTIFACT_SCHEMA_VERSION",
    "TabularArtifact",
    "build_backtest_artifact",
    "build_market_data_artifact",
    "OrderIntent",
    "OrderAction",
    "MultiLegOrder",
    "PortfolioTargets",
    "StrategyDecision",
    "Strategy",
    "Context",
    "Fill",
    "Position",
    "PositionEventType",
    "PositionSide",
    "TradePnL",
    "FundingCashFlow",
    "calc_trade_pnl",
    "side_multiplier",
    "simulate_fill",
    "calc_equity",
    "Backtest",
    "BacktestResult",
    "EquitySnapshot",
    "AllocationSnapshot",
    "PortfolioSnapshot",
    "PositionSnapshot",
    "TradeResult",
    "compute_all",
    "compute_signal_outcomes",
    "summarize_signal_mae_mfe",
    "generate_signal_mae_mfe_report",
    "compute_trade_lifecycle_outcomes",
    "summarize_trade_lifecycle_outcomes",
    "compute_trade_entry_outcomes",
    "summarize_trade_entry_outcomes",
    "generate_trade_tearsheet",
    "RunConfig",
    "ExecutionPolicy",
    "RiskPolicy",
    "RunMode",
    "LiveMode",
    "generate_run_id",
    "infer_timeframe",
    "to_ccxt",
    "to_canonical",
]
