"""Backtest engine, strategy protocol, cost model, and metrics.

Re-exports from subpackages for convenience.
"""

try:
    from ._version import __version__
except ImportError:
    # _version.py is generated by setuptools_scm at build/editable-install
    # time (gitignored, not committed) — missing only if librae is being
    # imported straight from a source tree that was never built/installed.
    __version__ = "0.0.0.dev0+unknown"

from .backtest.schema import (
    AllocationSnapshotPoint,
    BacktestOutput,
    EquityCurvePoint,
    PositionSnapshotPoint,
    RunMetadata,
    StrategyMetrics,
    RUN_ID_PATTERN,
)
from .backtest.engine import (
    AllocationSnapshot,
    Backtest,
    BacktestResult,
    EquitySnapshot,
    PortfolioSnapshot,
    PositionSnapshot,
)
from .core.cost_model import (
    CostModel,
    SymbolDescription,
    describe_symbols,
    margin_rate_from_absolute,
)
from .core.strategy import (
    OrderIntent,
    Strategy,
    Context,
    Fill,
    Position,
    PortfolioTargets,
    StrategyDecision,
)
from .core.executor import TradePnL, TradeResult, calc_trade_pnl, direction, make_fill
from .core.metrics import (
    compute_all,
    compute_signal_outcomes,
    compute_trade_entry_outcomes,
    compute_trade_lifecycle_outcomes,
    generate_signal_mae_mfe_report,
    generate_trade_tearsheet,
    summarize_signal_mae_mfe,
    summarize_trade_entry_outcomes,
    summarize_trade_lifecycle_outcomes,
)
from .core.run_config import ExecutionPolicy, RunConfig
from .core.utils import generate_run_id, infer_timeframe, to_ccxt, to_canonical
from .config.market_config import MarketConfig, get_market

__all__ = [
    "__version__",
    "BacktestOutput",
    "AllocationSnapshotPoint",
    "EquityCurvePoint",
    "PositionSnapshotPoint",
    "RunMetadata",
    "StrategyMetrics",
    "RUN_ID_PATTERN",
    "CostModel",
    "SymbolDescription",
    "describe_symbols",
    "margin_rate_from_absolute",
    "MarketConfig",
    "get_market",
    "OrderIntent",
    "PortfolioTargets",
    "StrategyDecision",
    "Strategy",
    "Context",
    "Fill",
    "Position",
    "TradePnL",
    "calc_trade_pnl",
    "direction",
    "make_fill",
    "Backtest",
    "BacktestResult",
    "EquitySnapshot",
    "AllocationSnapshot",
    "PortfolioSnapshot",
    "PositionSnapshot",
    "TradeResult",
    "compute_all",
    "compute_signal_outcomes",
    "summarize_signal_mae_mfe",
    "generate_signal_mae_mfe_report",
    "compute_trade_lifecycle_outcomes",
    "summarize_trade_lifecycle_outcomes",
    "compute_trade_entry_outcomes",
    "summarize_trade_entry_outcomes",
    "generate_trade_tearsheet",
    "RunConfig",
    "ExecutionPolicy",
    "generate_run_id",
    "infer_timeframe",
    "to_ccxt",
    "to_canonical",
]
